baseurl: http://cderv.rbind.io/
languageCode: en-us
title: cderv's blog
copyright: Christophe Dervieux
# Enable comments by entering your Disqus shortname
disqusShortname: ''
# Enable Google Analytics by entering your tracking code
googleAnalytics: ''
theme: ghostwriter
ignoreFiles:
  - \.Rmd$
  - _files$
  - _cache$
Author:
  name: Christophe Dervieux
  profile: ''
Taxonomies:
  tag: tags
Params:
  dateFormat: Mon, Jan 2, 2006
  description: A blog to share tips, tricks & findings about R ecosystem
  email: christophe.dervieux@gmail.com
  github: https://github.com/cderv
  gitlab: ''
  gplus: ''
  headline: Just another blog
  intro: yes
  linkedin: ''
  opengraph: yes
  shareFacebook: yes
  shareGooglePlus: no
  shareLinkedIn: no
  shareTwitter: yes
  stackoverflow: https://stackoverflow.com/users/3436535/titolondon
  twitter: https://twitter.com/chrisderv
Permalinks:
  post: /:year/:month/:day/:slug/
menu:
  main:
    - name: Blog
      url: /post/
      weight: 1
    - name: About
      url: /about/
      weight: 2
