baseurl = "http://cderv.rbind.io/"
languageCode = "en-us"
title = "cderv's blog"
copyright = "Christophe Dervieux"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""
theme = "ghostwriter"
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]

[Author]
    name = "Christophe Dervieux"
    profile = ""

[Taxonomies]
    tag = "tags"

[Params]
    intro = true
    headline = "Just another blog"
    description = "A blog to share tips, tricks & findings about R ecosystem"
    github = "https://github.com/cderv"
    gitlab = ""
    linkedin = ""
    gplus = ""
    twitter = "https://twitter.com/chrisderv"
    stackoverflow = "https://stackoverflow.com/users/3436535/titolondon"
    email = "christophe.dervieux@gmail.com"
    opengraph = true
    shareTwitter = true
    shareFacebook = true
    shareGooglePlus = false
    shareLinkedIn = false
    dateFormat = "Mon, Jan 2, 2006"

[Permalinks]
    post = "/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Blog"
    url = "/post/"
    weight = 1

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2

