baseurl: https://cderv.rbind.io/
languageCode: en-us
title: cderv's blog
copyright: Christophe Dervieux
# Enable comments by entering your Disqus shortname
disqusShortname: ''
# Enable Google Analytics by entering your tracking code
googleAnalytics: ''
theme: ghostwriter
ignoreFiles:
  - "\\.Rmd$"
  - "\\.Rmarkdown$"
  - "\\.knit\\.md$"
  - "\\.utf8\\.md$"
  - "_cache$"
author:
  name: Christophe Dervieux
  profile: ''
taxonomies:
  tag: tags
params:
  mainSections:
    - post
  intro: true
  headline: Just another blog
  description: A blog to share tips, tricks & findings about R ecosystem
  github: https://github.com/cderv
  gitlab: https://gitlab.com/cderv
  twitter: https://twitter.com/chrisderv
  linkedin: https://www.linkedin.com/in/cderv/
  stackoverflow: https://stackoverflow.com/users/3436535/titolondon
  email: christophe.dervieux@gmail.com
  opengraph: true
  shareTwitter: yes
  shareFacebook: yes
  shareGooglePlus: no
  shareLinkedIn: no
  dateFormat: Mon, Jan 2, 2006
  rss: true
  exponeaJsUrl: ""
  exponeaTarget: ""
  exponeaToken: ""
  exponeaTrackVisits: false
  readingTime: true
  readingTimeText: "Estimated reading time:"
  fathomUrl: ""
  fathomSiteId: ""
  plausibleAnalytics:
    domain: ""
    # Default value is plausible.io, overwrite this if you are self-hosting or using a custom domain
    serverURL: ""

# chrome highlighting
pygmentsUseClasses: false
pygmentsCodefences: false
    
permalinks:
  post: /:year/:month/:day/:slug/
  talk: "/talk/:filename/"

menu:
  main:
    - name: Blog
      url: /
      weight: 1
    - name: Talks
      url: /talk/
      weight: 2
    - name: About
      url: /about/
      weight: 3

markup:
  defaultMarkdownHandler: "goldmark"
  highlight:
    codeFences: false
    guessSyntax: false
    hl_Lines: ""
    lineNoStart: 1
    lineNos: false
    lineNumbersInTable: true
    noClasses: true
    tabWidth: 2
  goldmark:
    renderer:
      unsafe: true
      
privacy:
  disqus:
    disable: true
  googleAnalytics:
    anonymizeIP: true
    respectDoNotTrack: true
    useSessionStorage: false
