baseurl = "http://choreographer-dog-82283.netlify.com/"
languageCode = "en-us"
title = "cderv's blog"
copyright = "Christophe Dervieux"
# Enable comments by entering your Disqus shortname
disqusShortname = ""
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""
theme = "ghostwriter"

[Author]
    name = "Christophe Dervieux"
    profile = ""

[Taxonomies]
    tag = "tags"

[Params]
    intro = true
    headline = "Just another blog"
    description = "A blog to share tips, tricks & findings about R ecosystem"
    github = "https://github.com/cderv"
    gitlab = ""
    linkedin = ""
    gplus = ""
    twitter = "https://twitter.com/cderv"
    stackoverflow = "https://stackoverflow.com/users/3436535/titolondon"
    email = "christophe.dervieux@gmail.com"
    opengraph = true
    shareTwitter = true
    shareFacebook = true
    shareGooglePlus = true
    shareLinkedIn = false
    dateFormat = "Mon, Jan 2, 2006"

[Permalinks]
    post = "/:year/:month/:day/:filename/"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2

